### ISSUE TITLE
roadmap for rm2fb v1

### ISSUE THREAD

**Issue by raisjn** [ddvk/remarkable2-framebuffer#16]
here is tentative plan for rm2fb:

## Phase 1: (investigation)

* [x] figure out how to draw to screen
* [x] figure out where xochitl keeps its memory

## Phase 2: (compatibility)

* [x] get a simple app for rM1 working on rM2
* [x] find out what needs to be done for all apps to upgrade

## Phase 3: (single apps)

* [ ] articulate upgrade path for rM1 apps
  * [x] input handling
  * [ ] battery path
  * [x] rm2fb shim
* [x] create simple way of launching an app over SSH

## Phase 4: (distribution)

* [x] implement / adapt a launcher to launch apps with the rm2fb client shim
* [x] add ability to screenshot xochitl
* [x] add ability to screenshot rm2fb
* [x] add toltec packages for rm2fb

## Phase 5: (beyond)

* [ ] rm2fb protocol v2: support windowed / split screen applications 
* [ ] implement SWTCON that uses waveforms to draw to screen
* [ ] swap current rm2fb server to use open source SWTCON
* [ ] look into FUSE filesystem for /dev/fb0

**Comment by raisjn** [comment]
rm2fb is now in toltec testing, closing this issue
